# Generated by Django 3.2.6 on 2022-11-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите аватар', null=True, upload_to='pictures/', verbose_name='Аватарка'),
        ),
    ]
